version: '3.4'

services:
  spike-auth-service:
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      SERVER_PORT: ${SERVER_PORT}
      FRIENDS_BASE_URL: ${FRIENDS_BASE_URL}
      SERVER_SSL_PRIVATE_KEY: ${SERVER_SSL_PRIVATE_KEY}
      SERVER_SSL_CERTIFICATE: ${SERVER_SSL_CERTIFICATE}
      SPIKE_CLIENT_ID: ${SPIKE_CLIENT_ID}
      SPIKE_CLIENT_SECRET: ${SPIKE_CLIENT_SECRET}
      SPIKE_TOKEN_URL: ${SPIKE_TOKEN_URL}
      SPIKE_REDIRECT_TOKEN_URL: ${SPIKE_REDIRECT_TOKEN_URL}
      FRIENDS_API_AUDIENCE_ID: ${FRIENDS_API_AUDIENCE_ID}
      SPIKE_FRIENDS_SCOPE: ${SPIKE_FRIENDS_SCOPE}
      SPIKE_REDIRECT_URI: ${SPIKE_REDIRECT_URI}
      SPIKE_GRANT_TYPE: ${SPIKE_GRANT_TYPE}
